spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
mybatis:
  # 配置XML映射文件中指定的实体类别名路径
  type-aliases-package: com.huzhirong.top.ssm.modules.*.pojo
  # 配置MyBatis的xml配置文件路径
  mapper-locations: classpath:mappers/*/*.xml
  configuration:
    # 配置驼峰命名规则
    map-underscore-to-camel-case: true
    # 配置打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

